name: crafty_bay
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Add fonts section if custom fonts are used
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: path/to/font_regular.ttf
  #       - asset: path/to/font_bold.ttf
  #         weight: 700
  #   - family: AnotherFontFamily
  #     fonts:
  #       - asset: path/to/another_font_regular.ttf
